// Restored from ref/webview/assets/app-initial~app-main~worktree-init-v2-page~appgen-publication-terms-route~remote-conversati~oykv7gy7-B4ar2dlW.js
// Compatibility aliases for restored publication-terms resource handling.
export {
  initPublicationTermsHandlerRegistryChunk as A,
  mcpCapabilityMentionServersByHostState as B,
  getArtifactImportKindForPath as C,
  createMimeTypesModule as D,
  shouldParseArtifactPreviewForImportKind as E,
  localMcpCapabilityCatalogState as F,
  findMatchingMcpCapabilityFileViewer as G,
  getMcpServerLogo as H,
  localMcpCapabilityFileViewersState as I,
  createFileViewerToolArguments as K,
  mcpCapabilityFileViewersByHostState as L,
  READ_FILE_SAMPLE_MAX_FILE_BYTES as M,
  initReadFileMetadataLimitsChunk as N,
  initOpenFileCommandChunk as O,
  initMcpCapabilityCatalogChunk as P,
  globalMcpCapabilityEntryPointsState as R,
  initUnsupportedPreviewTypeChunk as S,
  initArtifactImportPresentationChunk as T,
  initMcpServerLogoHelpers as U,
  mcpCapabilityEntryPointsState as V,
  createMcpFileViewerHostResource as W,
  initWorkspaceResourceOpenerChunk as _,
  initFileReferenceActionMessagesChunk as a,
  getResourcePreviewParseMode as b,
  initOpenInTargetHelpersChunk as c,
  isEditorOpenTarget as d,
  filterOpenTargets as f,
  initClipboardWriterChunk as g,
  copyToClipboardPayload as h,
  selectOpenInTargets as i,
  openWorkspaceResource as v,
  prefetchOpenInTargets as o,
  selectPrimaryOpenTarget as p,
  initMcpResourceReadParamsChunk as q,
  createOpenInTargetsQueryOptions as r,
  copyWorkspaceFileContents as s,
  fetchWorkspaceFileContextMenuItems as t,
  initWorkspaceFileContextMenuChunk as u,
  registerPublicationTermsSidePanelHandler as j,
  sendOpenFileCommand as k,
  buildOpenTargetContextMenuItems as l,
  initOpenTargetContextMenuItemsChunk as m,
  buildWorkspaceFileContextMenuItems as n,
  getArtifactImportPresentation as w,
  getUnsupportedPreviewType as x,
  getReviewPreviewKind as y,
  localMcpCapabilityMentionServersState as z,
} from "../../appgen/publication-terms";

export * from "../../appgen/publication-terms";
