// Restored from ref/webview/assets/thread-overflow-menu-CM-Eo7JH.js
// Runtime bindings for thread overflow actions, side chat, and heartbeat automation tabs.
import {
  $j as initSideConversationProducer,
  $N as initDeveloperInstructionsProducer,
  AB as initScopeRuntime,
  ak as initSideConversationPromptProducer,
  cM as initToastRuntime,
  cm as conversationHostIdSignal,
  cP as initThreadActionMenuRuntime,
  Db as buildInstructionOverrides,
  FB as useScope,
  IB as useSignalValue,
  I_ as initRouteScope,
  JV as initReactRuntime,
  mP as logger,
  M_ as localConversationRouteScope,
  mv as initCurrentRefViewRuntime,
  Ob as initConversationCacheProducer,
  ok as runConversationAction,
  Op as initHostConversationActionsProducer,
  Ov as useNavigate,
  pP as initConversationActionAndLoggerRuntime,
  PB as useScopedValue,
  Sm as threadSourceSignal,
  SV as initQueryRuntime,
  tM as modelSelectionSignal,
  TV as useSignalSnapshot,
  uM as toastSignal,
  uP as useThreadCommandHandler,
  Up as conversationCollaborationModeSignal,
  Wp as conversationModelOverrideSignal,
  YN as sendHostRequest,
} from "../vendor/appg-thread-shared-runtime";
import {
  Ga as initElectronPlatformContent,
  ii as closeSideChatThreadAssociation,
  Ln as initKeyboardModifierState,
  Rn as useCommandRegistration,
  ri as initToastProducer,
  Si as initThreadOverflowQueryRuntime,
  ti as registerSideChatThreadAssociation,
  Wa as PlatformContentGate,
  xi as RenameThreadDialog,
} from "../vendor/pull-request-thread-actions-runtime";
import {
  _c as getPanelController,
  a as forkConversationFromLatest,
  b as initForkThreadMessages,
  C as useThreadActions,
  c as localEnvironmentSelectionsByWorkspaceSignal,
  Cn as initForkDialogLocalIcon,
  ed as bottomPanelActivationSignal,
  Ga as MoreHorizontalIcon,
  Ka as initMoreHorizontalIcon,
  kn as initForkDialogWorktreeIcon,
  l as initPendingWorktreeNavigationRoute,
  n as initProjectsAppProducer,
  o as createForkConversationPendingWorktree,
  On as WorktreeForkIcon,
  rd as rightPanelActivationSignal,
  S as useThreadPinControls,
  sd as initThreadPanelProducer,
  Sn as LocalForkIcon,
  So as initWorkspaceRouteHelpers,
  s as initThreadActionMessages,
  t as SideChatIcon,
  wo as isSideChatUnavailable,
  x as threadActionMessages,
  yc as initNavigationProducer,
  Yi as threadActionShortcutSignal,
} from "../vendor/projects-app-shared-runtime";
import {
  Ar as initAutomationPanelRuntime,
  Du as initProfileRouteProducer,
  Eu as LoadingPanel,
  gm as initHeartbeatAutomationTabsRuntime,
  hm as HeartbeatAutomationIcon,
  Jm as initCreateHeartbeatAutomationRuntime,
  jr as openExistingHeartbeatAutomationTab,
  Mr as openCreateHeartbeatAutomationTab,
} from "../vendor/profile-page-runtime";

const initConversationActionProducer = initConversationActionAndLoggerRuntime;
const initLoggerRuntime = initConversationActionAndLoggerRuntime;

export {
  bottomPanelActivationSignal,
  buildInstructionOverrides,
  closeSideChatThreadAssociation,
  conversationCollaborationModeSignal,
  conversationHostIdSignal,
  conversationModelOverrideSignal,
  createForkConversationPendingWorktree,
  forkConversationFromLatest,
  getPanelController,
  HeartbeatAutomationIcon,
  initAutomationPanelRuntime,
  initConversationActionProducer,
  initConversationCacheProducer,
  initCreateHeartbeatAutomationRuntime,
  initCurrentRefViewRuntime,
  initDeveloperInstructionsProducer,
  initElectronPlatformContent,
  initForkDialogLocalIcon,
  initForkDialogWorktreeIcon,
  initForkThreadMessages,
  initHeartbeatAutomationTabsRuntime,
  initHostConversationActionsProducer,
  initKeyboardModifierState,
  initLoggerRuntime,
  initMoreHorizontalIcon,
  initNavigationProducer,
  initPendingWorktreeNavigationRoute,
  initProfileRouteProducer,
  initProjectsAppProducer,
  initQueryRuntime,
  initReactRuntime,
  initRouteScope,
  initScopeRuntime,
  initSideConversationProducer,
  initSideConversationPromptProducer,
  initThreadActionMenuRuntime,
  initThreadActionMessages,
  initThreadOverflowQueryRuntime,
  initThreadPanelProducer,
  initToastProducer,
  initToastRuntime,
  initWorkspaceRouteHelpers,
  isSideChatUnavailable,
  LoadingPanel,
  localConversationRouteScope,
  localEnvironmentSelectionsByWorkspaceSignal,
  LocalForkIcon,
  logger,
  modelSelectionSignal,
  MoreHorizontalIcon,
  openCreateHeartbeatAutomationTab,
  openExistingHeartbeatAutomationTab,
  PlatformContentGate,
  registerSideChatThreadAssociation,
  RenameThreadDialog,
  rightPanelActivationSignal,
  runConversationAction,
  sendHostRequest,
  SideChatIcon,
  threadActionMessages,
  threadActionShortcutSignal,
  threadSourceSignal,
  toastSignal,
  useCommandRegistration,
  useNavigate,
  useScope,
  useScopedValue,
  useSignalSnapshot,
  useSignalValue,
  useThreadActions,
  useThreadCommandHandler,
  useThreadPinControls,
  WorktreeForkIcon,
};
