// Restored from ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js
// Public barrel for the app-initial~app-main~onboarding shared commons chunk —
// preserves the chunk's full 1280-symbol export contract for its 148 consumers.
//
// The chunk's APP CODE is semantically restored across restored/ domain folders
// (composer/, review/, conversations/, onboarding/, terminal/, automations/, ui/,
// plugins/, worktree/, image-side-panel/, utils/, app-shell/, …) and bundled VENDOR
// libs (react, react-dom, react-intl, xterm, d3, @dnd-kit, anser, rrule, marked) are
// boundary-ized to their npm packages. This barrel currently re-exports the live
// symbols from the original chunk so the public contract resolves while the per-symbol
// wiring to the restored modules is completed (open boundary; see RESTORATION_PLAN.md).
// @ts-nocheck

export { $, $S, $_, $a, $b, $c, $d, $f, $g, $h, $i, $l, $m, $n, $o, $p, $r, $s, $t, $u, $v, $x, $y, A, AC, AS, A_, Aa, Ab, Ac, Ad, Af, Ag, Ah, Ai, Al, Am, An, Ao, Ap, Ar, As, At, Au, Av, Ax, Ay, B, BS, B_, Ba, Bb, Bc, Bd, Bf, Bg, Bh, Bi, Bl, Bm, Bn, Bo, Bp, Br, Bs, Bt, Bu, Bv, Bx, By, C, CC, CS, C_, Ca, Cb, Cc, Cd, Cf, Cg } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { Ch, Ci, Cl, Cm, Cn, Co, Cp, Cr, Cs, Ct, Cu, Cv, Cx, Cy, D, DC, DS, D_, Da, Db, Dc, Dd, Df, Dg, Dh, Di, Dl, Dm, Dn, Do, Dp, Dr, Ds, Dt, Du, Dv, Dx, Dy, E, EC, ES, E_, Ea, Eb, Ec, Ed, Ef, Eg, Eh, Ei, El, Em, En, Eo, Ep, Er, Es, Et, Eu, Ev, Ex, Ey, F, FC, FS, F_, Fa, Fb, Fc, Fd, Ff, Fg, Fh, Fi, Fl, Fm, Fn, Fo, Fp, Fr } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { Fs, Ft, Fu, Fv, Fx, Fy, G, GS, G_, Ga, Gb, Gc, Gd, Gf, Gg, Gh, Gi, Gl, Gm, Gn, Go, Gp, Gr, Gs, Gt, Gu, Gv, Gx, Gy, H, HS, H_, Ha, Hb, Hc, Hd, Hf, Hg, Hh, Hi, Hl, Hm, Hn, Ho, Hp, Hr, Hs, Ht, Hu, Hv, Hx, Hy, I, IC, IS, I_, Ia, Ib, Ic, Id, If, Ig, Ih, Ii, Il, Im, In, Io, Ip, Ir, Is, It, Iu, Iv, Ix, Iy, J, JS, J_, Ja } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { Jb, Jc, Jd, Jf, Jg, Jh, Ji, Jl, Jm, Jn, Jo, Jp, Jr, Js, Jt, Ju, Jv, Jx, Jy, K, KS, K_, Ka, Kb, Kc, Kd, Kf, Kg, Kh, Ki, Kl, Km, Kn, Ko, Kp, Kr, Ks, Kt, Ku, Kv, Kx, Ky, L, LC, LS, L_, La, Lb, Lc, Ld, Lf, Lg, Lh, Li, Ll, Lm, Ln, Lo, Lp, Lr, Ls, Lt, Lu, Lv, Lx, Ly, M, MC, MS, M_, Ma, Mb, Mc, Md, Mf, Mg, Mh, Mi, Ml, Mm } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { Mn, Mo, Mp, Mr, Ms, Mt, Mu, Mv, Mx, My, N, NC, NS, N_, Na, Nb, Nc, Nd, Nf, Ng, Nh, Ni, Nl, Nm, Nn, No, Np, Nr, Ns, Nt, Nu, Nv, Nx, Ny, O, OC, OS, O_, Oa, Ob, Oc, Od, Of, Og, Oh, Oi, Ol, Om, On, Oo, Op, Or, Os, Ot, Ou, Ov, Ox, Oy, P, PC, PS, P_, Pa, Pb, Pc, Pd, Pf, Pg, Ph, Pi, Pl, Pm, Pn, Po, Pp, Pr, Ps, Pt, Pu, Pv } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { Px, Py, Q, QS, Q_, Qa, Qb, Qc, Qd, Qf, Qg, Qh, Qi, Ql, Qm, Qn, Qo, Qp, Qr, Qs, Qt, Qu, Qv, Qx, Qy, R, RC, RS, R_, Ra, Rb, Rc, Rd, Rf, Rg, Rh, Ri, Rl, Rm, Rn, Ro, Rp, Rr, Rs, Rt, Ru, Rv, Rx, Ry, S, SC, SS, S_, Sa, Sb, Sc, Sd, Sf, Sg, Sh, Si, Sl, Sm, Sn, So, Sp, Sr, Ss, St, Su, Sv, Sx, Sy, T, TC, TS, T_, Ta, Tb, Tc } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { Td, Tf, Tg, Th, Ti, Tl, Tm, Tn, To, Tp, Tr, Ts, Tt, Tu, Tv, Tx, Ty, U, US, U_, Ua, Ub, Uc, Ud, Uf, Ug, Uh, Ui, Ul, Um, Un, Uo, Up, Ur, Us, Ut, Uu, Uv, Ux, Uy, V, VS, V_, Va, Vb, Vc, Vd, Vf, Vg, Vh, Vi, Vl, Vm, Vn, Vo, Vp, Vr, Vs, Vt, Vu, Vv, Vx, Vy, W, WS, W_, Wa, Wb, Wc, Wd, Wf, Wg, Wh, Wi, Wl, Wm, Wn, Wo, Wp, Wr } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { Ws, Wt, Wu, Wv, Wx, Wy, X, XS, X_, Xa, Xb, Xc, Xd, Xf, Xg, Xh, Xi, Xl, Xm, Xn, Xo, Xp, Xr, Xs, Xt, Xu, Xv, Xx, Xy, Y, YS, Y_, Ya, Yb, Yc, Yd, Yf, Yg, Yh, Yi, Yl, Ym, Yn, Yo, Yp, Yr, Ys, Yt, Yu, Yv, Yx, Yy, Z, ZS, Z_, Za, Zb, Zc, Zd, Zf, Zg, Zh, Zi, Zl, Zm, Zn, Zo, Zp, Zr, Zs, Zt, Zu, Zv, Zx, Zy, _, _C, _S, __, _a } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { _b, _c, _d, _f, _g, _h, _i, _l, _m, _n, _o, _p, _r, _s, _t, _u, _v, _x, _y, a, aC, aS, a_, aa, ab, ac, ad, af, ag, ah, ai, al, am, an, ao, ap, ar, as, at, au, av, ax, ay, b, bC, bS, b_, ba, bb, bc, bd, bf, bg, bh, bi, bl, bm, bn, bo, bp, br, bs, bt, bu, bv, bx, by, c, cC, cS, c_, ca, cb, cc, cd, cf, cg, ch, ci, cl } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { cm, cn, co, cp, cr, cs, ct, cu, cv, cx, cy, d, dC, dS, d_, da, db, dc, dd, df, dg, dh, di, dl, dm, dn, do, dp, dr, ds, dt, du, dv, dx, dy, eC, eS, e_, ea, eb, ec, ed, ef, eg, eh, ei, el, em, en, eo, ep, er, es, et, eu, ev, ex, ey, f, fC, fS, f_, fa, fb, fc, fd, ff, fg, fh, fi, fl, fm, fn, fo, fp, fr, fs, ft, fu, fv } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { fx, fy, g, gC, gS, g_, ga, gb, gc, gd, gf, gg, gh, gi, gl, gm, gn, go, gp, gr, gs, gt, gu, gv, gx, gy, h, hC, hS, h_, ha, hb, hc, hd, hf, hg, hh, hi, hl, hm, hn, ho, hp, hr, hs, ht, hu, hv, hx, hy, i, iC, iS, i_, ia, ib, ic, id, if, ig, ih, ii, il, im, in, io, ip, ir, is, it, iu, iv, ix, iy, j, jC, jS, j_, ja, jb } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { jc, jd, jf, jg, jh, ji, jl, jm, jn, jo, jp, jr, js, jt, ju, jv, jx, jy, k, kC, kS, k_, ka, kb, kc, kd, kf, kg, kh, ki, kl, km, kn, ko, kp, kr, ks, kt, ku, kv, kx, ky, l, lC, lS, l_, la, lb, lc, ld, lf, lg, lh, li, ll, lm, ln, lo, lp, lr, ls, lt, lu, lv, lx, ly, m, mC, mS, m_, ma, mb, mc, md, mf, mg, mh, mi, ml, mm } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { mn, mo, mp, mr, ms, mt, mu, mv, mx, my, n, nC, nS, n_, na, nb, nc, nd, nf, ng, nh, ni, nl, nm, nn, no, np, nr, ns, nt, nu, nv, nx, ny, o, oC, oS, o_, oa, ob, oc, od, of, og, oh, oi, ol, om, on, oo, op, or, os, ot, ou, ov, ox, oy, p, pC, pS, p_, pa, pb, pc, pd, pf, pg, ph, pi, pl, pm, pn, po, pp, pr, ps, pt, pu, pv } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { px, py, q, qS, q_, qa, qb, qc, qd, qf, qg, qh, qi, ql, qm, qn, qo, qp, qr, qs, qt, qu, qv, qx, qy, r, rC, rS, r_, ra, rb, rc, rd, rf, rg, rh, ri, rl, rm, rn, ro, rp, rr, rs, rt, ru, rv, rx, ry, s, sC, sS, s_, sa, sb, sc, sd, sf, sg, sh, si, sl, sm, sn, so, sp, sr, ss, st, su, sv, sx, sy, t, tC, tS, t_, ta, tb, tc } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { td, tf, tg, th, ti, tl, tm, tn, to, tp, tr, ts, tt, tu, tv, tx, ty, u, uC, uS, u_, ua, ub, uc, ud, uf, ug, uh, ui, ul, um, un, uo, up, ur, us, ut, uu, uv, ux, uy, v, vC, vS, v_, va, vb, vc, vd, vf, vg, vh, vi, vl, vm, vn, vo, vp, vr, vs, vt, vu, vv, vx, vy, w, wC, wS, w_, wa, wb, wc, wd, wf, wg, wh, wi, wl, wm, wn } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
export { wo, wp, wr, ws, wt, wu, wv, wx, wy, x, xC, xS, x_, xa, xb, xc, xd, xf, xg, xh, xi, xl, xm, xn, xo, xp, xr, xs, xt, xu, xv, xx, xy, y, yC, yS, y_, ya, yb, yc, yd, yf, yg, yh, yi, yl, ym, yn, yo, yp, yr, ys, yt, yu, yv, yx, yy, z, zS, z_, za, zb, zc, zd, zf, zg, zh, zi, zl, zm, zn, zo, zp, zr, zs, zt, zu, zv, zx, zy } from "../ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js";
